python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/1A4Y/1A4Y_B.pdb B 1A4Y_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/1ALD/1ALD_A.pdb A 1ALD_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/1ALY/1ALY_A.pdb A 1ALY_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/1APZ/1APZ_A.pdb A 1APZ_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/1BZ1/1BZ1_A.pdb A 1BZ1_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/1BZ4/1BZ4_A.pdb A 1BZ4_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/1DXT/1DXT_B.pdb B 1DXT_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/1EYB/1EYB_A.pdb A 1EYB_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/1FGG/1FGG_A.pdb A 1FGG_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/1FYH/1FYH_B.pdb B 1FYH_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/1FZC/1FZC_B.pdb B 1FZC_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/1G73/1G73_A.pdb A 1G73_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/1GR3/1GR3_A.pdb A 1GR3_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/1H7S/1H7S_A.pdb A 1H7S_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/1HDR/1HDR_A.pdb A 1HDR_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/1HGU/1HGU_A.pdb A 1HGU_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/1HP7/1HP7_A.pdb A 1HP7_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/1HWG/1HWG_B.pdb B 1HWG_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/1HZD/1HZD_A.pdb A 1HZD_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/1I0Z/1I0Z_A.pdb A 1I0Z_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/1I3M/1I3M_A.pdb A 1I3M_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/1IK9/1IK9_A.pdb A 1IK9_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/1IVY/1IVY_B.pdb B 1IVY_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/1JCN/1JCN_A.pdb A 1JCN_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/1KR2/1KR2_A.pdb A 1KR2_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/1L4D/1L4D_A.pdb A 1L4D_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/1LMT/1LMT_A.pdb A 1LMT_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/1LYW/1LYW_B.pdb B 1LYW_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/1M73/1M73_E.pdb E 1M73_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/1NNL/1NNL_B.pdb B 1NNL_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/1NST/1NST_A.pdb A 1NST_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/1NTG/1NTG_A.pdb A 1NTG_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/1OIZ/1OIZ_A.pdb A 1OIZ_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/1OOK/1OOK_G.pdb G 1OOK_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/1PV8/1PV8_B.pdb B 1PV8_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/1QO5/1QO5_A.pdb A 1QO5_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/1RX0/1RX0_A.pdb A 1RX0_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/1SI4/1SI4_B.pdb B 1SI4_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/1T65/1T65_A.pdb A 1T65_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/1T94/1T94_A.pdb A 1T94_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/1TJJ/1TJJ_A.pdb A 1TJJ_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/1U59/1U59_A.pdb A 1U59_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/1UMK/1UMK_A.pdb A 1UMK_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/1URO/1URO_A.pdb A 1URO_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/1WAR/1WAR_A.pdb A 1WAR_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/1WM5/1WM5_A.pdb A 1WM5_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/1WSR/1WSR_A.pdb A 1WSR_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/1WUU/1WUU_B.pdb B 1WUU_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/1Y1H/1Y1H_X.pdb X 1Y1H_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/1YTQ/1YTQ_A.pdb A 1YTQ_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/1Z6Z/1Z6Z_A.pdb A 1Z6Z_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/1Z83/1Z83_A.pdb A 1Z83_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/1ZN8/1ZN8_B.pdb B 1ZN8_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/2A01/2A01_A.pdb A 2A01_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/2A1U/2A1U_B.pdb B 2A1U_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/2A1X/2A1X_A.pdb A 2A1X_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/2AEX/2AEX_A.pdb A 2AEX_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/2BFF/2BFF_A.pdb A 2BFF_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/2BV5/2BV5_A.pdb A 2BV5_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/2C9Y/2C9Y_A.pdb A 2C9Y_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/2CW6/2CW6_A.pdb A 2CW6_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/2EYI/2EYI_A.pdb A 2EYI_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/2FBY/2FBY_A.pdb A 2FBY_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/2FIM/2FIM_B.pdb B 2FIM_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/2G76/2G76_A.pdb A 2G76_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/2GCG/2GCG_A.pdb A 2GCG_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/2H11/2H11_A.pdb A 2H11_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/2H2N/2H2N_A.pdb A 2H2N_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/2H5G/2H5G_B.pdb B 2H5G_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/2I1M/2I1M_A.pdb A 2I1M_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/2IB8/2IB8_D.pdb D 2IB8_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/2IDX/2IDX_C.pdb C 2IDX_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/2ILR/2ILR_A.pdb A 2ILR_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/2IZZ/2IZZ_C.pdb C 2IZZ_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/2JIF/2JIF_A.pdb A 2JIF_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/2NZ2/2NZ2_A.pdb A 2NZ2_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/2OAT/2OAT_A.pdb A 2OAT_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/2OBV/2OBV_A.pdb A 2OBV_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/2ODU/2ODU_A.pdb A 2ODU_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/2PID/2PID_B.pdb B 2PID_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/2PRL/2PRL_A.pdb A 2PRL_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/2PUQ/2PUQ_H.pdb H 2PUQ_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/2Q4R/2Q4R_A.pdb A 2Q4R_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/2QD1/2QD1_A.pdb A 2QD1_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/2QTZ/2QTZ_A.pdb A 2QTZ_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/2R0N/2R0N_A.pdb A 2R0N_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/2R3V/2R3V_A.pdb A 2R3V_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/2VIG/2VIG_A.pdb A 2VIG_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/2VKQ/2VKQ_A.pdb A 2VKQ_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/2VT5/2VT5_A.pdb A 2VT5_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/2VXP/2VXP_A.pdb A 2VXP_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/2WK6/2WK6_A.pdb A 2WK6_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/2WUL/2WUL_A.pdb A 2WUL_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/2XSW/2XSW_A.pdb A 2XSW_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/2XT3/2XT3_A.pdb A 2XT3_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/2XWT/2XWT_C.pdb C 2XWT_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/2XZE/2XZE_A.pdb A 2XZE_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/2Y23/2Y23_A.pdb A 2Y23_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/2Y7J/2Y7J_A.pdb A 2Y7J_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/2ZEJ/2ZEJ_B.pdb B 2ZEJ_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/3A1F/3A1F_A.pdb A 3A1F_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/3A40/3A40_X.pdb X 3A40_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/3BFN/3BFN_A.pdb A 3BFN_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/3BH7/3BH7_B.pdb B 3BH7_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/3BPS/3BPS_A.pdb A 3BPS_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/3BPT/3BPT_A.pdb A 3BPT_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/3BRB/3BRB_B.pdb B 3BRB_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/3BUR/3BUR_A.pdb A 3BUR_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/3D9S/3D9S_A.pdb A 3D9S_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/3DKB/3DKB_A.pdb A 3DKB_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/3E77/3E77_A.pdb A 3E77_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/3ECR/3ECR_A.pdb A 3ECR_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/3EXE/3EXE_B.pdb B 3EXE_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/3F7B/3F7B_A.pdb A 3F7B_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/3FGQ/3FGQ_A.pdb A 3FGQ_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/3FJO/3FJO_A.pdb A 3FJO_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/3FS1/3FS1_A.pdb A 3FS1_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/3G2F/3G2F_A.pdb A 3G2F_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/3GKJ/3GKJ_A.pdb A 3GKJ_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/3GMZ/3GMZ_A.pdb A 3GMZ_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/3H3G/3H3G_A.pdb A 3H3G_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/3IAR/3IAR_A.pdb A 3IAR_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/3KCG/3KCG_I.pdb I 3KCG_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/3KJP/3KJP_A.pdb A 3KJP_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/3KWB/3KWB_X.pdb X 3KWB_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/3L81/3L81_A.pdb A 3L81_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/3LC3/3LC3_A.pdb A 3LC3_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/3LQ3/3LQ3_A.pdb A 3LQ3_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/3LWK/3LWK_A.pdb A 3LWK_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/3MDY/3MDY_A.pdb A 3MDY_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/3NH6/3NH6_A.pdb A 3NH6_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/3NJ4/3NJ4_A.pdb A 3NJ4_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/3OP5/3OP5_A.pdb A 3OP5_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/3PDF/3PDF_A.pdb A 3PDF_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/3QIC/3QIC_A.pdb A 3QIC_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/3QK3/3QK3_B.pdb B 3QK3_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/3R8Q/3R8Q_A.pdb A 3R8Q_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/3R9A/3R9A_C.pdb C 3R9A_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/3RFE/3RFE_A.pdb A 3RFE_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/3RMU/3RMU_A.pdb A 3RMU_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/3RQS/3RQS_B.pdb B 3RQS_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/3S5N/3S5N_A.pdb A 3S5N_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/3SC0/3SC0_A.pdb A 3SC0_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/3SKP/3SKP_A.pdb A 3SKP_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/3SW0/3SW0_X.pdb X 3SW0_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/3TEG/3TEG_A.pdb A 3TEG_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/3TK0/3TK0_A.pdb A 3TK0_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/3UP1/3UP1_A.pdb A 3UP1_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/3ZE2/3ZE2_D.pdb D 3ZE2_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/3ZQS/3ZQS_A.pdb A 3ZQS_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/3ZYC/3ZYC_D.pdb D 3ZYC_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/4A9C/4A9C_B.pdb B 4A9C_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/4ANP/4ANP_A.pdb A 4ANP_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/4APO/4APO_B.pdb B 4APO_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/4ASC/4ASC_A.pdb A 4ASC_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/4ASE/4ASE_A.pdb A 4ASE_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/4AY9/4AY9_X.pdb X 4AY9_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/4B7L/4B7L_B.pdb B 4B7L_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/4BSJ/4BSJ_A.pdb A 4BSJ_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/4CAI/4CAI_A.pdb A 4CAI_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/4CC0/4CC0_A.pdb A 4CC0_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/4CG4/4CG4_A.pdb A 4CG4_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/4CH8/4CH8_H.pdb H 4CH8_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/4CJ6/4CJ6_A.pdb A 4CJ6_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/4CVH/4CVH_A.pdb A 4CVH_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/4D0E/4D0E_A.pdb A 4D0E_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/4DM9/4DM9_A.pdb A 4DM9_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/4DO4/4DO4_B.pdb B 4DO4_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/4F0I/4F0I_B.pdb B 4F0I_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/4FVL/4FVL_A.pdb A 4FVL_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/4FVQ/4FVQ_A.pdb A 4FVQ_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/4G84/4G84_A.pdb A 4G84_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/4GR7/4GR7_A.pdb A 4GR7_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/4GS7/4GS7_C.pdb C 4GS7_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/4GT4/4GT4_A.pdb A 4GT4_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/4H4F/4H4F_A.pdb A 4H4F_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/4HL4/4HL4_A.pdb A 4HL4_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/4IDQ/4IDQ_A.pdb A 4IDQ_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/4IQM/4IQM_A.pdb A 4IQM_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/4IRQ/4IRQ_C.pdb C 4IRQ_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/4J15/4J15_A.pdb A 4J15_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/4JA8/4JA8_A.pdb A 4JA8_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/4K33/4K33_A.pdb A 4K33_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/4KY9/4KY9_A.pdb A 4KY9_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/4M9P/4M9P_A.pdb A 4M9P_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/4O33/4O33_A.pdb A 4O33_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/4O9S/4O9S_A.pdb A 4O9S_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/4OKH/4OKH_B.pdb B 4OKH_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/4P0J/4P0J_A.pdb A 4P0J_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/4P5W/4P5W_A.pdb A 4P5W_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/4PED/4PED_A.pdb A 4PED_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/4QAM/4QAM_B.pdb B 4QAM_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/4RHP/4RHP_B.pdb B 4RHP_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/4RKK/4RKK_A.pdb A 4RKK_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/4S0Z/4S0Z_A.pdb A 4S0Z_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/4TTB/4TTB_A.pdb A 4TTB_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/4UM9/4UM9_B.pdb B 4UM9_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/4WND/4WND_A.pdb A 4WND_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/4WNU/4WNU_C.pdb C 4WNU_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/4WXQ/4WXQ_A.pdb A 4WXQ_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/4X30/4X30_A.pdb A 4X30_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/4X4W/4X4W_A.pdb A 4X4W_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/4XEO/4XEO_A.pdb A 4XEO_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/4XO7/4XO7_A.pdb A 4XO7_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/5A0C/5A0C_A.pdb A 5A0C_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/5A5I/5A5I_A.pdb A 5A5I_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/5BON/5BON_A.pdb A 5BON_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/5BV7/5BV7_A.pdb A 5BV7_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/5BV8/5BV8_A.pdb A 5BV8_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/5C1Z/5C1Z_A.pdb A 5C1Z_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/5CV0/5CV0_A.pdb A 5CV0_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/5DU3/5DU3_A.pdb A 5DU3_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/5E26/5E26_B.pdb B 5E26_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/5E2P/5E2P_A.pdb A 5E2P_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/5EH1/5EH1_A.pdb A 5EH1_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/5FQD/5FQD_B.pdb B 5FQD_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/5I9Y/5I9Y_A.pdb A 5I9Y_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/5IN3/5IN3_B.pdb B 5IN3_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/5J1T/5J1T_A.pdb A 5J1T_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/5KWY/5KWY_C.pdb C 5KWY_vars.ls
python /dors/capra_lab/users/sliwosgr/ml_tools/custom_features/neighborhood_features/gen_neighbor_features.py /dors/capra_lab/users/sliwosgr/pathdig/ddGprep_out0/5LGD/5LGD_A.pdb A 5LGD_vars.ls
